<?php
if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

$dictionary['Properties'] = array(
    'table' => 'properties',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'mls_id' => array(
            'name' => 'mls_id',
            'vname' => 'LBL_MLS_ID',
            'type' => 'varchar',
            'len' => '50',
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'unified_search' => true,
        ),
        'street_address' => array(
            'name' => 'street_address',
            'vname' => 'LBL_STREET_ADDRESS',
            'type' => 'varchar',
            'len' => '255',
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'unified_search' => true,
        ),
        'city' => array(
            'name' => 'city',
            'vname' => 'LBL_CITY',
            'type' => 'varchar',
            'len' => '100',
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'unified_search' => true,
        ),
        'state' => array(
            'name' => 'state',
            'vname' => 'LBL_STATE',
            'type' => 'enum',
            'options' => 'state_list',
            'len' => '2',
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
        ),
        'zip_code' => array(
            'name' => 'zip_code',
            'vname' => 'LBL_ZIP_CODE',
            'type' => 'varchar',
            'len' => '10',
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
        ),
        'price' => array(
            'name' => 'price',
            'vname' => 'LBL_PRICE',
            'type' => 'currency',
            'len' => '26,6',
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
        ),
        'currency_id' => array(
            'name' => 'currency_id',
            'type' => 'id',
            'group' => 'currency_id',
            'vname' => 'LBL_CURRENCY',
            'function' => array(
                'name' => 'getCurrencyDropDown',
                'returns' => 'html'
            ),
        ),
        'status' => array(
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'options' => 'property_status_list',
            'len' => '25',
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
        ),
        'bedrooms' => array(
            'name' => 'bedrooms',
            'vname' => 'LBL_BEDROOMS',
            'type' => 'int',
            'len' => 11,
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
        ),
        'bathrooms' => array(
            'name' => 'bathrooms',
            'vname' => 'LBL_BATHROOMS',
            'type' => 'decimal',
            'len' => '3,1',
            'precision' => 1,
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
        ),
        'square_footage' => array(
            'name' => 'square_footage',
            'vname' => 'LBL_SQUARE_FOOTAGE',
            'type' => 'int',
            'len' => 11,
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
        ),
        'main_photo' => array(
            'name' => 'main_photo',
            'vname' => 'LBL_MAIN_PHOTO',
            'type' => 'image',
            'dbType' => 'varchar',
            'len' => '255',
            'importable' => false,
            'duplicate_merge' => 'disabled',
        ),
        // Relationships
        'contacts' => array(
            'name' => 'contacts',
            'type' => 'link',
            'relationship' => 'properties_contacts',
            'source' => 'non-db',
            'module' => 'Contacts',
            'bean_name' => 'Contact',
            'vname' => 'LBL_CONTACTS',
        ),
        'opportunities' => array(
            'name' => 'opportunities',
            'type' => 'link',
            'relationship' => 'properties_opportunities',
            'source' => 'non-db',
            'module' => 'Opportunities',
            'bean_name' => 'Opportunity',
            'vname' => 'LBL_TRANSACTIONS',
        ),
        'documents' => array(
            'name' => 'documents',
            'type' => 'link',
            'relationship' => 'documents_properties',
            'source' => 'non-db',
            'module' => 'Documents',
            'bean_name' => 'Document',
            'vname' => 'LBL_DOCUMENTS',
        ),
    ),
    'relationships' => array(
        'properties_contacts' => array(
            'lhs_module' => 'Properties',
            'lhs_table' => 'properties',
            'lhs_key' => 'id',
            'rhs_module' => 'Contacts',
            'rhs_table' => 'contacts',
            'rhs_key' => 'id',
            'relationship_type' => 'many-to-many',
            'join_table' => 'properties_contacts',
            'join_key_lhs' => 'property_id',
            'join_key_rhs' => 'contact_id',
        ),
        'properties_opportunities' => array(
            'lhs_module' => 'Properties',
            'lhs_table' => 'properties',
            'lhs_key' => 'id',
            'rhs_module' => 'Opportunities',
            'rhs_table' => 'opportunities',
            'rhs_key' => 'id',
            'relationship_type' => 'many-to-many',
            'join_table' => 'properties_opportunities',
            'join_key_lhs' => 'property_id',
            'join_key_rhs' => 'opportunity_id',
        ),
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('Properties', 'Properties', array('basic', 'assignable', 'security_groups'));