<?php
$module_name = 'RE_Properties';
$searchdefs [$module_name] = array(
    'layout' => array(
        'basic_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'property_address' => array(
                'type' => 'varchar',
                'label' => 'LBL_PROPERTY_ADDRESS',
                'width' => '10%',
                'default' => true,
                'name' => 'property_address',
            ),
            'property_city' => array(
                'type' => 'varchar',
                'label' => 'LBL_PROPERTY_CITY',
                'width' => '10%',
                'default' => true,
                'name' => 'property_city',
            ),
            'status' => array(
                'type' => 'enum',
                'label' => 'LBL_STATUS',
                'width' => '10%',
                'default' => true,
                'name' => 'status',
            ),
            'property_type' => array(
                'type' => 'enum',
                'label' => 'LBL_PROPERTY_TYPE',
                'width' => '10%',
                'default' => true,
                'name' => 'property_type',
            ),
            'current_user_only' => array(
                'name' => 'current_user_only',
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
        'advanced_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'property_address' => array(
                'type' => 'varchar',
                'label' => 'LBL_PROPERTY_ADDRESS',
                'width' => '10%',
                'default' => true,
                'name' => 'property_address',
            ),
            'property_city' => array(
                'type' => 'varchar',
                'label' => 'LBL_PROPERTY_CITY',
                'width' => '10%',
                'default' => true,
                'name' => 'property_city',
            ),
            'property_state' => array(
                'type' => 'varchar',
                'label' => 'LBL_PROPERTY_STATE',
                'width' => '10%',
                'default' => true,
                'name' => 'property_state',
            ),
            'property_postalcode' => array(
                'type' => 'varchar',
                'label' => 'LBL_PROPERTY_POSTALCODE',
                'width' => '10%',
                'default' => true,
                'name' => 'property_postalcode',
            ),
            'status' => array(
                'type' => 'enum',
                'label' => 'LBL_STATUS',
                'width' => '10%',
                'default' => true,
                'name' => 'status',
            ),
            'property_type' => array(
                'type' => 'enum',
                'label' => 'LBL_PROPERTY_TYPE',
                'width' => '10%',
                'default' => true,
                'name' => 'property_type',
            ),
            'mls_id' => array(
                'type' => 'varchar',
                'label' => 'LBL_MLS_ID',
                'width' => '10%',
                'default' => true,
                'name' => 'mls_id',
            ),
            'listing_price' => array(
                'type' => 'currency',
                'label' => 'LBL_LISTING_PRICE',
                'currency_format' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'listing_price',
            ),
            'bedrooms' => array(
                'type' => 'int',
                'label' => 'LBL_BEDROOMS',
                'width' => '10%',
                'default' => true,
                'name' => 'bedrooms',
            ),
            'bathrooms' => array(
                'type' => 'decimal',
                'label' => 'LBL_BATHROOMS',
                'width' => '10%',
                'default' => true,
                'name' => 'bathrooms',
            ),
            'square_footage' => array(
                'type' => 'int',
                'label' => 'LBL_SQUARE_FOOTAGE',
                'width' => '10%',
                'default' => true,
                'name' => 'square_footage',
            ),
            'year_built' => array(
                'type' => 'int',
                'label' => 'LBL_YEAR_BUILT',
                'width' => '10%',
                'default' => true,
                'name' => 'year_built',
            ),
            'listing_date' => array(
                'type' => 'date',
                'label' => 'LBL_LISTING_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'listing_date',
            ),
            'assigned_user_id' => array(
                'name' => 'assigned_user_id',
                'label' => 'LBL_ASSIGNED_TO',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_user_array',
                    'params' => array(false),
                ),
                'default' => true,
                'width' => '10%',
            ),
        ),
    ),
    'templateMeta' => array(
        'maxColumns' => '3',
        'maxColumnsBasic' => '4',
        'widths' => array(
            'label' => '10',
            'field' => '30',
        ),
    ),
);